### ISSUE TITLE
test 만들기 시작하기

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#14]
제일 간단한 테스트를 만들어 보겠습니다.

학습목표:
- "django에서 테스트를 만들고 실행한다는 것은 어떻게 돌아가는 것인가"를 이해한다.
- 테스트용 db를 생성하고 관리해야 함을 이해한다.
- model을 이용한 코드를 테스트해본다.

실행:
* `Book`을 생성하는 코드가 제대로 동작하는지 확인하는 테스트를 짜보자.

다음의 코드가 동작하는 것을 테스트가 확인해 주도록 해주세요:

```python
book = Book.objects.create(title="스토너")
```

---

- 참조: [Testing in Django](https://docs.djangoproject.com/en/1.9/topics/testing/)에 있는 문서들 중 가장 먼저 소개된 [Writing and running tests](https://docs.djangoproject.com/en/1.9/topics/testing/overview/)를 읽어보세요. 그 뒤의 문서들은 아직 안 봐도 됩니다.

- model, view 등 모든 부분은 테스트 가능합니다. 단 model이 가장 단순하기 때문에 (db가 붙어있음에도 불구하고!) 주로 이를 이용한 단위테스트를 만드는 데 집중하도록 할게요.

- 다음편 예고: 제가 model에 추가해 달라고 할 메소드를 있습니다. 빨리 이거 끝내고 그걸 짜주세요.

**Comment by jangxyz** [comment]
수고하셨습니다. 짝짝짝~

**Comment by snailzzang** [comment]
얏호~  감격스런 첫 테스트!
감사합니다 ㅎㅎ
