### ISSUE TITLE
Quote Test 만들기

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#16]
1. 다른 모델에 dependency가 있는 Quote를 만들어 본다.
  1. User를 생성한다.
  2. Book을 생성한다.
  3. user와 book을 들고 있는 Quote를 생성한다.

      ```python
     quote = Quote.create(user=user, book=book, quotation="봐, 나는 살아있어!")
      ```

    ※ 사진 파일도 같이 테스트하는건 안 하셔도 됩니다. 

2. created_at과 updated_at이 저장되는지 테스트한다.
  1. ... quote를 생성하고, 거기에 `created_at`과 `updated_at`에 '적당한' 값이 들어갔는지 확인한다.
  2. 다시 그 quote 를 저장하고, `updated_at`만 갱신되는 것을 확인한다.

---

Django의 User 모델이 어떻게 생겼는지는 [Using the Django authentication system](https://docs.djangoproject.com/en/1.9/topics/auth/default/) 를 참고하세요.

여기까지 하시면, 이제 제가 필요한 메소드를 만들어달라고 부탁(..)할 수 있게 됩니다.

**Comment by snailzzang** [comment]
2번 커밋했습니다. 
  
1) QuoteTestCase.setUp은 앞의 파일에 있습니다. 
- 제가 1번 2번이 한 문제인 줄 모르고, 1번만 풀어서 먼저 커밋했었거든요.
- 2번째 커밋에는 1번 커밋때 제출한 setUp 부분이 빠져있을 거에요. 그 부분에는 변경이 없었기 때문에. 

2) 테스트함수는 2가지 버전으로 짰습니다. 
- test_Quote_is_correctly_created : 이건 좀더 심플한 버전입니다.
- test_Quote_time_is_correctly_created : 이건 created_at, updated_at에 포커스를 두고, 시간이 좀더 '적당히 시간스럽게' 들어갔는지 확인하기 위한, 두번째 테스트코드입니다.
