### ISSUE TITLE
test 개선

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#19]
#17 에서 구현한 테스트를 좀 더 의미있게 바꿔보는 작업을 합니다.

test_functions.py를 test_image_resizing.py로 변경했습니다.
테스트가 바뀐 부분을 명확히 살펴보고, 새로 난 에러를 해결해 주세요.

이름:
* '이미지 테스트'는 보다 더 명확한 이름을 지어주세요.
* 테스트하려는 대상에 따라 TestCase를 나눠주세요.
* 한 테스트 메소드에서 여러가지를 테스트하지 마세요.
* '제대로 동작하는지 테스트' 와 같이 의미 없는 이름은 가급적 붙이지 마세요.

데이터 파일:
- 테스트에 사용될 데이터는 `tests/fixtures/` 밑에 두기로 합니다.
- 테스트로 인해 생성되는 이미지 파일은 `tests/media/` 아래 두기로 합니다.
- 테스트로 인해 생성되는 파일은 테스트 이후에 삭제합니다.

**Comment by jangxyz** [comment]
수고하셨습니다.

다음 단계 <strike> 던전</strike>  테스트가 열렸습니다. 74ed2d7bc28a50cc1cac633d89d482ce76d6d1f4
테스트에 맞게 코드를 수정해 주세요!

(그 다음 단계도 기다리고 있습니다)

**Comment by jangxyz** [comment]
이제 '이미지에 필요한 처리를 하는 작업'은 view에서 model로 옮겨갔습니다.

view의 주 임무는 사용자의 request 를 분석하고, 필요한 작업을 model 등에 위임한 다음, 그 결과를 적절한 템플릿으로 변환하여 response를 반환하는 것입니다.
이미지 크기를 보고 적당한 처리 작업을 하는 것은 view에 적합하지가 않죠. 그래서 model에다 죄다 줘 버리고 맡긴겁니다. 지금은 model에 들어갔지만, 나중에 필요하면 또 다른 데로 빠질지도 몰라요.

---

새 테스트가 추가되었습니다. [test_image_resizing_quote.py](https://github.com/snailzzang/bookocr/blob/6b8799c90f413a01ed1cb63139c800d4f27850ff/bookshot/tests/test_image_resizing_quote.py)

이번에는 classmethod가 아니라 다시 일반 인스턴스 메소드가 되었습니다.
테스트에 있는 코드처럼 쓰고 싶습니다:

```python
	self.quote.photo = SimpleUploadedFile(name='IMG_6114.jpg', content=self.image_content, content_type='image/jpeg')

	# resize
	self.quote.resize_image()
	self.quote.save()
```

이걸 계기로, view는 "리사이징을 해라"라고 Quote에 요청하는 것 외에는 상관하지 않게 됩니다.

* class의 인스턴스 메소드를 구현하세요.
* 필요하면, 기존의 staticmethod (와 그 테스트) 도 옮기거나 바꾸세요.
* 이에 맞게 작동하도록 views 코드를 수정하세요.

**Comment by snailzzang** [comment]
인스턴스 메소드를 구현하던  브랜치를 임시로 올려두었습니다. 여전히 저장하는 부분에서 딥 고통을 겪고 있는데 한번 봐주세요~

**Comment by jangxyz** [comment]
이전 코드도 잘 돌게 고쳐주세요.

**Comment by snailzzang** [comment]
깨지는 기존 test 코드를 수정하였습니다.

**Comment by jangxyz** [comment]
test용 media 파일들은 별도의 경로에 관리하도록 해주세요.

`test_image_resizing_quote.py` 에서 이미 처리된 부분입니다. `test_image_resizing.py` 에서는 개발용 데이터들과 섞여서 관리되고 있습니다.

**Comment by snailzzang** [comment]
테스트용 미디어 파일을 write할, 테스트용 media_root를 추가했습니다. 이제 테스트 이미지가 실제 데이터와 섞이지 않습니다.
