### ISSUE TITLE
이미지 크롭

### ISSUE THREAD

**Issue by snailzzang** [snailzzang/bookocr#20]

**Comment by jangxyz** [comment]
잘 적용하셨네요. ^^ 제가 test_image_resizing에 적용했던 개선들이 잘 나타나 있군요.
crop 기능 자체는 PIL을 불러오는 수준이지만, resize 때 겪었던 혼란을 정리해 볼 좋은 기회인거 같네요.

이쯤에서 몇가지 생각해 보아야 할 문제...

### 왓 투 테스트

* 테스트는 짜야겠는데... 뭘 검증하는 테스트를 짜지?

    지금은, 체크해보는 바가 `Image` 객체가 있는가, 가로 세로 크기가 내가 지정한 대로 나왔는가.. 정도네요.
    (다시 보니, 파일이 생성되었는 지조차도 테스트 만으론 알 수가 없군요)

    당초 계획한 기능은 **이미지를 crop 하자** 인데.
    이미지가 crop이 되었는다는 것을 확인해 봐야 하는건가?

    그런데 여기서 '어떻게 crop을 테스트할까'를 좀 더 생각해 보다 보면...

* crop은 사실 PIL이 하는건데, 내가 그게 제대로 구현되었나 검증해봐야 하는건가?

    뭐 Pillow도 나름 [image crop에 대한 테스트](https://github.com/python-pillow/Pillow/blob/master/Tests/test_image_crop.py)가 있네요.
    당연하겠죠. 그것 자체가 Pillow가 제공하는 기능이니, 걔네가 테스트와 코드를 만들었을테죠.
    그렇다면 저 코드를 참고해서 내가 또 비슷한 테스트 코드를 짜야 하나? 그럼 나는 내 코드를 검증하는게 아니라 쟤네 코드를 검증하는게 되는건가?

    '솔직히 나보다 PIL 개발자가 더 잘 알 것 아님?'

이쯤에서 단위 테스트에 대해 생각해 봅시다.

짧은 대답은 "안 그래도 된다"입니다.

긴 대답은... (얘기가 길어집니다... 편하게 들으세요) '단위 테스트가 뭐지?'부터 생각해보자는 거죠.

**단위 테스트**는, 필요한 가장 작은 단위 별로 각자가 테스트해보자는 겁니다.
    image crop 기능은 이미 Pillow가 테스트를 하였기 때문에 된거죠. 내가 그것을 다시 테스트할 필요는 없습니다.

물론 나는 '이미지를 crop하자'는 기능을 구현하고 있기 때문에 그에 필요한 코드(와 테스트)를 짤테지만,
그 중 (사실상) 핵심 기능은 이미 라이브러리에서 테스트와 구현이 되어 있네요.
그럼 내가 '검증'해야 하는 것은 무엇인가?
이미 구현이 완료되었기 때문에 테스트가 필요 없는 것인가?
서말이라도 꿰어야 보배니까, 실제로 꿰었는지를 또 검사해야 하는건가?

여기에서 이른 바 테스트에 대한 *행위주의자* 와 *상태주의자* 간의 이견이 생깁니다. (저는 딱 부러지는 대답은 안 났다고 봅니다.)
상태주의자(혹은 고전주의자)가 바라보는 검증이란: 테스트 전에 상태를 설정하고, 코드를 실행한 뒤에, 그로 인한 결과를 살펴보며 확인해본다.
행위주의자가 바라보는 검증: 검증이란 '무엇이다'를 확인하는 과정이 아니라 '어떻게 할 것이다'를 확인하는 과정이다. 검증 전·후의 상태를 바라보는 것은 진정한 검증이 아니다.

즉 행위주의자 관점에서는, 이미지가 실제로 crop 되었는지를 검증할 것이 아니라, 실제 PIL에게 검증을 요청했는 지를 검증해야 하는 것이죠. "최대리, 내가 요청한거 어떻게 됐어?" "네, 관련부서에 전달했습니다." 그걸 제대로 했는지 안 했는지는 더 이상 내 소관이 아니라 그것을 전달 받은 부서(혹은 객체, 혹은 라이브러리..)의 책임입니다. 그리고 그것이 제대로 되는지는 그 쪽의 단위테스트가 보장해주는 것이구요.
이것이 단위테스트가 바라보는 이상적인 세계입니다.

행위주의자들이 말하는 행위주도개발(BDD, Behavior Driven Development)의 이상대로라면,
이미지를 파일에 저장하는 것도, DB에서 (지금 테스트와 상관 없는) 다른 모델을 생성하는 것도 위반입니다.
"나는 Quote 객체에 이미지가 저장이 잘 되는지를 확인하려는 건데, 왜 굳이 User 모델을 생성하는 코드가 들어가야 하냐" ([test_models.py](https://github.com/snailzzang/bookocr/blob/d53406df5266a0345617329c85e9c84c85e0c2c1/bookshot/tests/test_models.py#L22))

이에 대한 대답은 궁색할 수 밖에 없습니다. 그 코드를 테스트하기 위해서가 아니라, 현재 구현된 방식이 그 부분을 필요로 하기 때문에 그런 것 뿐이죠. 심지어 그 모델을 갖고 별다른거 하지 않는 경우도 부기지수입니다.
그래서 행위주의자들은, "테스트에 통과하기에 충분한 가짜 객체"를 생성하라고 합니다. User 모델을 필요로 하는거 같으면, 그냥 User 모델처럼 행동하는 가짜 객체(mock이라고 부릅니다)를 넣어줘. 

```python
	Quote.objects.create(
		user=UserMock(username='가짜사람'),
		book=BookMock(title='가짜책'),
		quotation="봐, 나는 살아있어!")
```

파일을 기록하는 코드가 있다면 실제 파일이 생성되는 것이 아니라, 파일 기록 행위를 흉내내는 객체가 있으면 됩니다.
`open('abc.txt', 'w')`가 있으면 가짜 `open` 함수를 제공하는 식이죠. 나중엔 "DB, 그거 꼭 필요해?" 까지도 갑니다.

이게 그들이 얘기하는 진정한 '단위 테스트'인 거죠.

BDD의 접근은 흥미로운게 많습니다. TDD와 BDD들끼리 서로 싸우면서 이게 맞네 너는 틀리네 하고 있는데, 다른 사람들이 보기엔 '테스트는 피곤한거구나' 싶기도 합니다.
여기서 착각하면 안될 건 둘 다 기본 취지에는 100% 동감하고 있다는 겁니다. '의도가 드러나는 코드(spec)를 먼저 작성하고, 이 것이 제대로 동작하게끔 구현한다'. 테스트 코드를 나중에 쓰거나 안 쓰란 얘긴 전혀 아닙니다. (도킨스와 굴드가 싸우는데 기독교가 좋아합니다..)

이야기가 길어졌는데 (이제 BDD만 소개했을 뿐인데!), 얘기하고 싶은 바는 이것입니다:
- BDD와 TDD라는 재밌는 세력들이 있다. ([Martin Fowler의 유명한 글](http://martinfowler.com/articles/mocksArentStubs.html), [BDD하는 사람들은 이런 것도 만들었어요](http://lettuce.it/index.html))
- '어떻게 하면 잘 테스트할지'는 몹시 어려운 문제이다. 완성된 솔루션이 없기 때문에 고민을 멈출 수가 없다.


### 아, 그리고

crop을 요청하는 client와 view 코드는 제가 작업하도록 하겠습니다.
그 동안은 일단 resize 코드 자체에 대한 리팩토링을 좀 하고 계시지요 (#19)
