### ISSUE TITLE
user.recent_books() 메소드 생성

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#21]
### 사용자의 최근 책을 알려주는 메소드 작성

User 모델에 "최근에 내가 등록한 문구의 책들"을 겹침없이 돌려주는 QuerySet 메소드 `recent_books`를 작성해주세요.
[QuerySet](https://docs.djangoproject.com/en/1.9/ref/models/querysets/)은 django orm이 `.get`이나 `.filter`, `.all` 등을 할 때 반환되는 값의 type입니다.

### 필요

제가 몇개 적어보니 책이름 자동완성이 훌륭하긴 한데
새 문구를 작성할 때마다 매번 책제목부터 작성하고, 네트워크 타고 가져온 결과 중에서 선택하고 하는게 시간이 걸리더라구요.

해서, 미리 '최근에 내가 적은 책 몇권'이 디폴트로 나왔으면 좋겠다는 생각이 들었습니다.

조만간 필요한 테스트를 작성해서 올리겠습니다. 그에 맞춰서 구현해 주시면 되겠어요.

*(한 일주일 동안 띄워져 있던 새 이슈 페이지인데 이제야 submit 하네요 ㅋ)*

**Comment by snailzzang** [comment]
user.recent_books() 메소드를 생성하였습니다. 테스트를 모두 통과하였습니다.

**Comment by jangxyz** [comment]
수고하셨습니다 ;)

몇가지 개선사항...


1. Quote의 updated_at을 Book에다 집어넣지 마세요. Book에 새 필드를 만들고, 관련 quote이 추가되면 같이 갱신되게 해주세요.

    지금은 잘 작동하는데, 다른 데에서 updated_at이 있는지 알고 사용하다가 문제가 될 수 있습니다. view에서는 template에 한번 쓰고 버릴 거라 그런 식의 데이터를 만드는게 장려되지만 model은 안정적으로 믿을만한 기능을 제공해야 합니다.

    가능하다면 이번엔 django에 있는 [signal](https://docs.djangoproject.com/en/1.9/topics/signals/)을 사용해서 해봅시다.


2. `User.add_to_class`는 사용하지 마세요. 문서화되지 않은 내부용 코드입니다. (see "[it's a very bad method](https://groups.google.com/d/msg/django-users/o12Uzhp4k7A/mc1pM7YQPkkJ)") Django의 [proxy model](https://docs.djangoproject.com/en/1.9/topics/db/models/#proxy-models)을 이용해서 해봅시다.

**Comment by jangxyz** [comment]
`User.add_to_class`를 다른 방법으로 대체하는 문제는 #27에서 다루기로 합니다.

**Comment by jangxyz** [comment]
생각해보았는데, `Book.updated_at`이 있어서 Quote가 저장될 때마다 갱신된다는 생각에 문제가 있네요. Here's why:

1. Book 자체에는 User 정보가 없기 때문에, 나 말고 다른 유저가 Quote를 등록해도 Book.updated_at 은 갱신된다.
2. 내가 user.recent_books를 가져올 때는 "나를 기준으로" 가져오는 것이다. 그러니까 book에 있는 updated_at의 내림차순이 아닐 수 있다.

그렇죠? 어떻게 하면 더 좋을까요? (2점)

**Comment by jangxyz** [comment]
distinct가 제대로 동작하지 않습니다. 다른 model의 attribute를 가지고 `order_by`를 쓸 때 나타나는 문제인거 같습니다. ([querysets#distinct](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#distinct))

테스트를 올렸습니다. 통과하도록 고쳐주세요. 

힌트: django 이슈라기보단 SQL 이슈네요. `annotate`를 이용해 보세요.

**Comment by snailzzang** [comment]
http://joelsaupe.com/programming/order-distinct-values-django/
위의 문서 등을 참고해서, 

books = Book.objects.filter(quote__user=self).order_by('-quote__updated_at').distinct()
==> 
books = Book.objects.filter(quote__user=self).annotate().order_by('-quote__updated_at')
이런 형태로 변경해봤는데, 전혀 먹히지가 않더라구요. (같은 결과가 나옴)

혹시 이런 방법 말고, annotate()를 쓰는 방법이 있을까요?

**Comment by snailzzang** [comment]
현재 풀어야 되는 이슈가 2가지인데요.  
1) book_updated_at 
2)  distinct()가 안먹히는 문제 

조금 고민을 해봤는데, 혹시 이런 방법은 어떨까 싶어요. 

- 현재 Book 테이블에 readers 필드가 있구요. 이 m2m 필드를 통해 book과 user가 연결되어 있습니다. 
- 그래서 DB를 열어보면, bookshot_book_readers라는 테이블이 자동으로 생성되고, 이 테이블이 book과 user의 foreignKey를 하나씩 가지고 있습니다. 
- 요 테이블에, updated_at이 추가되면 좋을 것 같습니다. 

- 여기에 필드를 추가하려면, 아예 모델을 명시적으로 새로 정의해야 될 듯하고요. models.py에  class UserBooks: 라는 것을 하나 새로 만드는 형태로요. 필드는 3개. book, user, updated_at
-  그러면, quote가 추가될때 book의 updated_at을 업데이트하면,  book_updated_at을 처리하는 문제가 해결될 것 같습니다. 
-  이 방식은 Quote 테이블을 참조하지 않기 때문에 중복된 book을 가져오지 않아서 distinct() 를 쓸 필요가 없어질듯 하고요.   물론 해봐야하겠지만요.

**Comment by jangxyz** [comment]
대답이 늦었습니다 ^^;

위에서 제시하는 방법은 "(reader x book) 테이블에 updated_at을 추가하고 그걸로 정렬하자"인거죠?
그래도 아마 될겁니다만.. M2M 자체도 복잡한데 거기다 또 필드 추가해서 따로 관리하려면... 일이 너무 커지는거 같죠.
처음의 방식으로 계속 접근해 봅시다.

### 원인

기존의 방식의 쿼리 문을 살펴보면 다음과 같습니다:

```python
books = Book.objects.filter(quote__user=self).order_by('-quote__updated_at').distinct()
print(books.query)
```

```SQL
SELECT DISTINCT 
  "bookshot_book"."id", "bookshot_book"."title", "bookshot_book"."isbn13", "bookshot_book"."cover_url", "bookshot_book"."_raw_response",
  "bookshot_quote"."updated_at" 
FROM "bookshot_book"
  INNER JOIN "bookshot_quote" ON ("bookshot_book"."id" = "bookshot_quote"."book_id")
WHERE "bookshot_quote"."user_id" = 1 
ORDER BY "bookshot_quote"."updated_at" DESC
```

(SQL 쿼리를 오랜만에 보는거라 잘 안 보이실테지만) 
자세히 살펴보면, `SELECT` 문 마지막에 `bookshot_quote.updated_at` 필드가 추가된 것을 보실 수 있어요.
정렬을 하기 위해서, "book에 연결돼 있는 quote의 수정 시각"도 가져오는거죠. 당연히 `.order_by('-quote__updated_at')` 때문입니다.

그러니까 `DISTINCT`이긴 한데, `[book]`에 대한 게 아니라 `[(book,quote)]`에 대해 distinct를 요청하고 있는거죠.
그래서 중복된 책들이 보이는 겁니다.

그럼 `quote.updated_at`을 가져오지 않고 정렬해주면 안되나요? 네 그럴 수 없습니다 ㅋㅋ
사실 `.order_by`에 "연관된 모델의 필드로 정렬하기(`quote__`)"가 들어간 지도 얼마 안됩니다. (저 할 때는 없었거든요) 그만큼 본래보다 확장된 기능이라는 얘기입니다.

그럼 어떻게 하느냐?

### annotate 란

annotate는 DB에서 많이 쓰이는 [aggregation](https://docs.djangoproject.com/en/1.9/topics/db/aggregation/)이라는 개념과 상관이 있습니다.

"현재 모은 값 중에서 max값을 보여줘", "avg를 보여줘"처럼
매 row마다 구할 수 있는 계산결과가 아니라 "전체 row들을 대표하는 값"을 계산하는 과정이죠.
엑셀의 SUM, AVG 랑 동일한 개념입니다. (기본적으로 데이터처리의 개념이 비슷비슷합니다. Big data 세계에서도 똑같아요)

aggregation을 하면 이제 보여줄 결과는 '그런 row들'의 집합 형태가 아니라 '그런 row들을 가지고 계산한 값 하나'가 돼 버립니다. 벡터가 아니라 스칼라죠.
```SQL
SELECT COUNT(*) FROM bookshot_book
```
하면 숫자만 딸랑 나오고 마는 것이죠.

이 값을 '다시 이용'하기 위해, `GROUP BY`라는 SQL 쿼리 명령어가 있습니다. row들을 다시 그루핑하는거죠.

예를 들어 볼게요.
"매일매일 TODO를 했는데, 월 별로 TODO 개수가 몇개인지 알고 싶다"고 해봐요.

```SQL
SELECT month, count(todo) as todos__count
FROM Todo
GROUP BY month
```
이렇게 하면 "Todo 테이블에서 월별로 그룹을 지어서, 각 그룹별로 todo를 세어서 month와 함께 보여줘" 정도가 되겠죠.
`[(1, 3), (2, 17), (3, 32), (4, 0), (5, 0) ... (12, 0)]` 이런 식으로 나오게 될겁니다.

이 때 `count(todo) as todos__count` 처럼, 각 그룹에 대해 aggregation한 결과를 다시 덧붙이는 작업을 장고에서  `annotation`이라고 부르는 겁니다.


### 전략

그러니까, 우리는 이렇게 바꾸면 됩니다.

- 기존: "책과 문구"의 벡터를 정렬한다. 여기다 `DISTINCT`를 요청하느라 중복 책이 발생
- 변경: "책과 문구"의 벡터를 "책을 기준으로 그루핑을 하되, 그룹 내에서 문구의 수정 시각의 MAX값을 가지고 있는다".

얘기가 길었습니다.
[Queryset API distinct() does not work?](http://stackoverflow.com/questions/453477/queryset-api-distinct-does-not-work/460702#460702) 이걸 참고해서 만들어 보시고, 결과 SQL 문을 여기 아래다 달아주세요.

**Comment by snailzzang** [comment]
앗,  위의 방법대로 수정해서 테스트 통과시킨 후에, (기쁜 나머지) 바로 커밋해버렸네요.
