### ISSUE TITLE
Book model에 isbn13과 cover를 저장

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#22]
#21 에서 리턴한 book 들을 보여주려면, 이미 저장돼 있는 cover 이미지가 있어야 합니다.

또 Google Books에서 반디로 엔진을 바꾸고 나니 isbn을 가져올 수 있게 되었습니다.
앞으로 이걸 book 기본 표지로 삼을까 생각 중입니다 (기존 book_id와 둘 중에 어느 것이 더 나을지, 생각해 봐야겠네요)

대략적인 구상입니다. 이에 맞춰 테스트도 작성해주시고, migration도 해주시고 구현도 해주세요 ㅋㄷ

필드: Book 모델에 `isbn13`, `cover_url`, `_raw_response` 필드를 추가한다.

ISBN:
* `isbn13` 이란 필드를 추가한다.
  - NULL이어서는 안 된다. 다만 이전 데이터나 값이 없는 경우가 있을 수는 있으니, 빈 문자열인 것은 허용한다.
*  isbn의 경우에 10자리와 13자리가 있는데, 통일성을 위해 언제나 저장되는 값은 isbn13으로 한다. 심지어 입력데이터가 isbn10이더라도, 내부적으로 isbn13으로 변환해서 저장하게 한다.
  - 어디 찾아보면 라이브러리가 있을거에요.
  - 대략:

    ````python
        # https://www.amazon.com/dp/1590171993
        book.isbn13 = '1590171993' # isbn10
        assertEqual(book.isbn13, "9781590171998") # isbn13
    ````
  - python class의 getter, setter를 재지정할 수 있는 방법이 있습니다. django model에서도 아마 사용가능하겠지요. 찾아보고, 혹시 장고에서 쓰는 더 나은 패턴 같은게 있다면 제안해주세요.
* isbn에 가끔 대시(-)가 들어가는 경우가 있던데, 그것도 빼고 저장하게 해주세요.
  -  대략

    ````python
        book.isbn13 = '978-1590171998'
        assertNotEqual(book.isbn13, '978-1590171998')
        assertEqual(book.isbn13, '9781590171998')
    ````

커버 이미지:
* `cover_url` 이란 필드를 추가한다.
  - URL형태입니다
  - NULL일 수도 있음

raw response:
* `_raw_response`란 필드를 추가한다.
  - 아마도 JSON형태의 문자열이 될 것입니다. Google Books나 Bandi에서 가져온 JSON을, 혹시 나중에 또 쓸 일이 있을까 싶어 저장해 둡니다.
  - NULL일 수도 있음
* 언더바(_)로 시작하는 이유는 내부적인, 은밀한 용도라는 의미입니다

**Comment by snailzzang** [comment]
TO DO: 
- python class의 getter, setter를 이용하는 방법으로 리팩토링하기

setter를 제대로 쓸 줄 몰라서 staticmethod를 써버렸습니다.  요 부분은 다시 제가 한번 찾아보고 코드를 개선해보겠습니다.

**Comment by jangxyz** [comment]
`ImportError: No module named 'jsonfield'`

에러가 나고 동작하지 않습니다.

**Comment by jangxyz** [comment]
https://docs.python.org/3/library/functions.html#property 이 문서를 참고하세요.

**Comment by snailzzang** [comment]
JsonField를 TextField로 변경했습니다.

**Comment by snailzzang** [comment]
setter와 property를 사용하여 리팩토링 하였습니다.

**Comment by jangxyz** [comment]
isbn13에 값을 지정하지 않으면 "00000000"이 들어가는데, 이런 가비지값이 들어가면
실제 사용하는 코드에서 "값이 제대로 들어가지 않았는지"를 검증하기가 어렵습니다.

매번 `if book.isbn13 == "0000000000000":` 로 확인해야 하는데, 딱히 큰 의미가 없는 검증코드입니다.

isbn13은 `blank=True`로 설정되어 있습니다.
`if book.isbn13:` 만으로 검증할 수 있게 해주세요. 테스트 추가했습니다.

**Comment by snailzzang** [comment]
isbn13의 디폴트 값을 제거했습니다.

**Comment by snailzzang** [comment]
그런데,  self.assertFalse(not not book.isbn13)  <=  여기에서, not not 문법이 뭔지 확실히 잘 몰라서, 긴가민가한 상태로 진행하긴 했어요. 처음에는 잘못 입력하신 줄 알았습니다.

**Comment by jangxyz** [comment]
파이썬에서 자주 쓰이는지 모르겠는데, 일반적으로 종종 쓰는 패턴입니다.

```python
    self.assertEqual(True, True)
    self.assertEqual(not True, False)

    self.assertNotEqual("a", True)
    self.assertEqual(not "a", False)
    self.assertEqual(not not "a", True)
```

보통 '`NULL`스럽지 않은 값'이면 if statement에 넣었을 때 `True`로 해석되긴 합니다만,
명시적으로 "난 `True`/`False`를 원해"라고 할 때 쓸 수 있는 방법입니다.

다른 언어에서는 주로 `!`가 `not`의 역할을 하기 때문에 간단히 `!!book.isbn13` 을 합니다.
파이썬은 가독성을 위해서 `!`을 버리고 `not`을 취했는데, 덕분에 별로 예쁘게 보이지 않네요.

**Comment by snailzzang** [comment]
감사합니다. 

이거는 이제 닫아도 되겠지요?
