### ISSUE TITLE
OCR update를 하는 view code 만들기

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#26]
페이지에서 문자인식하는 UI는 만들어져 있습니다. 이제 view가 반응하도록 해주면 됩니다.

현재 기능 작동 방식:

1. 로그인한 사용자가 "문구 추가하기" 버튼을 누른다.
    `/quotes/new` 로 이동

2. 책 제목과 문구 사진을 올리고 "다음" 버튼을 누른다.
    `POST /add` ==> `/books/1/quotes/13/recognize` 로 이동

3. 사진에서 인식할 영역을 선택하고 "자동 인식" 버튼을 누르면, 자바스크립트 코드가 AJAX로 `url  name='post_quote_ocr'` 에 요청한다. (페이지 변하지 않음)

4. **`views.quote.ocr_request`에서 입력을 가지고, `quote.read_image`에 요청한 후, 결과를 JsonResponse로 돌려주어야 한다**
  - 현재는 간단한 read_image가 구현되어 있음

5. 3번의 자바스크립트 코드가 AJAX 응답을 받아서 textarea에 결과를 적어준다. 사용자는 문구를 적당히 수정하고 "저장" 버튼을 누른다.
    `POST /books/1/quotes/13/ocr`

6. `views.quote.ocr_update` 에서 quote의 문구를 저장한다.
  (*함수 이름이 부적절한거 같아 추후 변경할 예정입니다*)

template과 model은 작성되어 있습니다. 이에 걸맞는 view를 만들어 주세요.

**Comment by snailzzang** [comment]
OCR update view 를 작성해서 커밋했습니다. 테스트를 통과했고, runserver에서도 잘 돌아가네요.

**Comment by jangxyz** [comment]
드디어 `JsonResponse`가 등장했군요 ^^
