### ISSUE TITLE
이미 저장돼 있는 책 바로 입력하기

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#28]
목표: 사용자로서 한 책에 있는 문구를 계속 올리기 위해, 가장 최근에 올린 책을 미리 선택할 수 있었으면 좋겠다.

사용자가 최근에 입력한 문구가 있으면,
책 제목 입력란에 focus를 가져가기만 해도 최근 책 3권이 나놔서 미리 선택할 수 있게 한다.

- this issue follows #22

**Comment by jangxyz** [comment]
@snailzzang `views.quote.add` 에서 book의 isbn13, cover_url, _raw_response 을 저장해 주세요.
`authors` 필드도 추가해서 저장해 주세요 (문자열)

**Comment by snailzzang** [comment]
book 테이블에 author 필드를 추가하면 되지요? 네~
