### ISSUE TITLE
사용자 제한하기

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#32]
우선은 지정된 몇명만 사용하도록 해보죠.

사용자가 Facebook으로 로그인 한 후에,
지정된 몇명이 아닌 사람들이면 강제로 로그아웃하게 해주세요.

(애초에 로그인도 안 되게 하면 가산점)
(강제 로그아웃 후에 적당한 메시지도 추가해주면 또 가산점)

**Comment by snailzzang** [comment]
제가 오늘 좀 부지런히 찾아봤더니,  developer.facebook.com에 좋은 기능이 있네요. 

- 페이스북 로그인 인증을 private으로 세팅해놓고     (현재는 public이라 모든 사람이 로그인 가능) 
- tester로  우리 그룹 사람들을 등록해놓으면 
- 우리 모임 분들만 페이스북 로그인이 가능합니다. 
- 서비스 자체는 오픈된 상태에서, 로그인만 제약하는 기능입니다. 
- 제가 저번에 장환님을 테스터로 등록할때처럼 등록하면 되는데, 어떤 노티스 이메일이나 그런 알림은 가지 않고요. 
- 접속했을때 로그인이 승인되면서 사용할 수 있게 됩니다. 

우리 모임 사람들만 사용하는 closed beta 모드에서는 이 기능을 한번 써보면 어떨까 싶네요. 보니깐, 이게 딱 이런 용도를 위해서 만들어진 것 같아요. 서비스는 오픈돼있지만 페이스북 로그인에만 제약을 거는 식. 등록된 사용자만 로그인되게요.

**Comment by snailzzang** [comment]
일단 이대로 한다음에, 유저들이 가입하면 ID를 받아 수정하는 것으로.

**Comment by jangxyz** [comment]
우선 된 것 같으니 이 티켓은 닫을게요~~
나중에 수정하는 건 따로.
