### ISSUE TITLE
같은 이미지 이름으로 올리면, 다른 사진에 overwrite 되는 이슈 해결하기

### ISSUE THREAD

**Issue by snailzzang** [snailzzang/bookocr#38]
**문제**
- 프로덕션 버전에서 이미지를 업로드하면 S3에 저장됩니다. 이때 같은 이름의 이미지 파일을 새로 올리면, 기존의 (동일한 파일명의) 이미지에 덮어쓰는 이슈가 발생하네요. 기존의 이미지가 없어집니다. 다른 사용자가 올린 이미지인 경우에도 overwrite 되는 듯합니다. 
- 로컬에서는 같은 이름의 이미지 파일이 업로드되면, 이미지 이름 뒤에  랜덤 캐릭터가 자동으로 덧붙여지면서 저장되어 이 문제가 발생하지 않았습니다. ex. book2_6JuYe1c.jpg 
- 다른 사용자간에 이미지 이름이 같을 경우는 상당히 많은데요. 특히 모바일에서 찍은 사진은 이미지네임이 숫자 형태로 자동생성되는 경우도 많고요. 이미지를 저장하는 과정에서 이 문제를 미리 처리해주는게 좋을듯합니다. 

**제안**
- 처음에 이미지를 저장할 때, filename에 'quote_id'를 앞에 prefix로 붙여서 저장하면 어떨까 싶습니다.  ex) image1.jpg 일 경우 ==> 38_image1.jpg 같은 형태로 변환하여 저장.
- user_id와 timestamp를 prefix로 붙이는 방안도 생각을 해봤는데, 이미지 주소에 user_id가 노출되는 이슈가 발생할 듯합니다. timestamp로 시간을 계산해서 넣어주는 것은 filename이 조금 길어지는 이슈가 있고요.(그래도 고려해볼만 함).  quote_id는 quote와 photo가 1:1이라 photo별로 unique하고, 또 심플해서 좋아보이네요.

**Comment by jangxyz** [comment]
아 S3에서는 이게 또 걸리는군요.

quote의 id를 쓰는 방식에는 한가지 문제가 있는데, Quote를 저장하기 전까진 `quote_id`를 알 수 없으므로, quote를 먼저 저장하고 나서 이미지를 다시 저장해야 한다는 문제가 생깁니다. db를 한번만 건드려도 되는걸 굳이 2번 건드릴 필요는 없을거 같아요.

지금 Django는 어떻게 하고 있는걸까요?
문서를 보면 `Storage` 클래스에 [get_available_name](https://docs.djangoproject.com/en/1.9/ref/files/storage/#django.core.files.storage.Storage.get_available_name)이란 메소드가 있네요. 현재는 다음과 같이 구현되어 있다고 합니다.

> If a file with name already exists, an underscore plus a random 7 character alphanumeric string is appended to the filename before the extension.

굳이 '원래 데이터랑 연결될만한 정보'가 필요하지 않다는게 신기하죠 :)
생각해보면 이미지 파일보고 다시 데이터를 알아야 할 필요가 없으니, 사실 아무렇게나 해도 겹치지만 않으면 상관 없습니다!


우선 `get_available_name`이란 메소드가 있다고 하니, 우리가 쓰는 S3 Storage 클래스가 저걸 어떻게 구현하고 있는지 봐야겠네요. 덮여 쓰이고 있다면 처리가 안되고 있는 것 같지만..

**Comment by snailzzang** [comment]
Storage 클래스에 get_available_name이란 메소드 써서 해결했습니다. 로컬에서 heroku 환경으로 세팅해놓고 S3에 이미지를 올려봤는데, 이미지 뒤에 underscore와 random 7 character가 잘 붙어서 나오네요. 

bugfix/file-overwrite 브랜치 따서 수정 후 각각 master와 release에 머지했습니다.

**Comment by jangxyz** [comment]
`AWS_S3_FILE_OVERWRITE` 라는 옵션이 있었군요 ^^ 용케 찾아내셨네요.

(그런데 댓글에는 왜 `get_available_name`을 사용해서 해결했다고 하신건가요..?)

**Comment by snailzzang** [comment]
.... 앗,  제가 옵션 설정만 바꾼 거였군요. 메쏘드에 들어가는 파라미터를 바꿔서... 그 메쏘드의 효과를 바꿨다고 생각을 하고 있었네요. (쑥쓰럼...)  

네 암튼 저 설정이 있어서, 간단히 해결할 수 있었습니다. 천만 다행!

**Comment by jangxyz** [comment]
잡았다 요놈!
