### ISSUE TITLE
책 정보를 가져올 수 없는 책 처리하기

### ISSUE THREAD

**Issue by snailzzang** [snailzzang/bookocr#40]
<천재들의 주사위>같이 절판된 책일 경우, 책 정보를 불러오기가 어려운 경우가 있는데요. 이처럼 책 정보가 없는 책을 등록한다음에, 다른 책을 등록하려고 new 버튼을 눌렀을 때 서버에러가 납니다. 

살펴봤더니, raw_response를 빈 값으로 가져오는 과정에서 에러가 났고요. 

이유는 다름이 아니라...  제가 지난번에 수정하면서 잘못 고쳤더라구요. (commit no : 203b244)
_raw_response의  default를 "{}"으로 세팅한다는 걸, 잘못해서 cover_url 의 default를 {}로 고치고 _raw_response의 디폴트는 None으로 남아있었습니다. Aㅏ..... 

그래서 책이 등록되는 것은 잘 되는데, 그 다음에 새로운 quote 를 등록할때 500 서버에러가 떴던 것이구요. 그 이유는 recent book 3권 정보를 가져오는 과정에서, 이전 책의 json 값이 어딘가에서 None으로 소환되서 에러가 나는듯 했씁니다. 

models.py에서 저 부분은 다시 수정하고 마이그레이션 파일도 만들어두었습니다. 
**아직 커밋은 안했는데  release v0.2.0으로 커밋하는 게 나을까요? 아니면 master로 커밋하는 게 좋을까요?** 
(지금 릴리즈와 마스터 버전이 꽤 차이가 나서, 푸시하는 부분에서 약간의 헷갈림이 있네요.)

**Comment by jangxyz** [comment]
Aㅏ....

**Comment by jangxyz** [comment]
다행스럽게도 [git flow](http://nvie.com/posts/a-successful-git-branching-model/) 정책에는 이런 종류의 문제에도 설명이 나와 있습니다 :)

우선, `bugfix/handle-empty-raw-response` 같은 이름으로 branch를 하나 만들고 거기서 작업을 합니다.
거기서 commit 하고 나면, 온전히 '버그만을 고친 수정사항'이 생기게 되죠.

이제 이걸, release branch에다가도 주입(merge)하고 master branch에다가도 주입시키는겁니다.
마치 백신을 만들어서 환자들한테 주사기로 따로따로 투약 하듯이요.

한꺼번에 3개의 브랜치를 신경써야 하니 헷갈린다는 느낌은 들겠지만, git은 원래 이렇게 쓰는겁니다.

**Comment by snailzzang** [comment]
bugfix로 브랜치 폴더 만들고 그 밑에 handle-empty-raw-response 브랜치 따서 수정 후에 master와 release 0.2.0에 각각 머지했습니다.

**Comment by jangxyz** [comment]
이번에는 잘 된건가요오... 나중에 또 문제 생기진 않겠죠?
migration 13.. 기억해 두겠습니다...
