### ISSUE TITLE
Crop_image에서 에러가 나는 문제 

### ISSUE THREAD

**Issue by snailzzang** [snailzzang/bookocr#41]
현재 crop_image를 하고 자동인식을 할 때, 에러가 나는 이슈가 있습니다. 저번에 같이 얘기했지만 S3 문제인 듯 하고요. S3에서 image path를 가져와서 Pillow로 Image.open() 하는 과정에서 에러가 나는듯합니다. 

이거 S3에서 이미지를 다운로드 받은 후 그 이미지 path로 열어서 crop해보니 자동인식까지 잘 동작합니다.  read_text_from_image 함수에서요.  (s3.meta.client.download_file)       

바로 열리면 좋은데, 안되면 이 방법이라도 써보면 어떨까 합니다.

**Comment by jangxyz** [comment]
S3boto 에서는 `.path`를 쓸 수 없다고 되어 있는 것 같더라구요.
우리가 저걸 쓰는 이유는 PIL에서 이미지를 접근하기 위해서였는데,
아마 path에 의한 접근 말고 직접 내용을 읽어올 수 있을 겁니다. 그렇게 해서 `Image`를 생성해 보도록 해보겠습니다.

**Comment by jangxyz** [comment]
헉. 이게 뭐죠...

**Comment by jangxyz** [comment]
b9976c7 에서 작업한 내용 설명입니다. 요는 "최대한 storage에서 이미 지원하는 기능을 사용한다"

- [ImageField#path](https://docs.djangoproject.com/en/1.9/ref/files/storage/#django.core.files.storage.Storage.path) 속성은 본디 모든 Storage에서 동작하는 메소드가 아니더라. (특히 S3boto!)
  파일의 경로를 언급하는 용도로 사용할 수 없다.

- Pillow에 파일의 경로가 아니라 [imagefield 인스턴스 자체를 넘겨도 된다](http://stackoverflow.com/a/22036239/1405998).
  애초에 경로를 신경 쓸 이유가 없었던 것이다.

- 파일의 확장자를 아는데는 `#path` 말고 [ImageField#name](https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.fields.files.FieldFile.name) 속성을 쓰는 것으로 충분하다.

그러므로 다음과 같은 변경사항이면 충분하다.
1. `os.path.splitext`에 `photo.name` 을 넣는다.
2. `Image.open`에 `self.photo`를 직접 넘긴다.
3. 완료

---

참조:

1.  ImageField#path: https://docs.djangoproject.com/en/1.9/ref/files/storage/#django.core.files.storage.Storage.path
2. how to go form django image field to PIL image and back?: http://stackoverflow.com/a/22036239/1405998
3. ImageField#name: https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.fields.files.FieldFile.name
