### ISSUE TITLE
운영 스크립트 개선

### ISSUE THREAD

**Issue by jangxyz** [snailzzang/bookocr#42]
현재 heroku 기반의 설정, django 기반의 설정 등이 섞여 있어 운영하기에 어렵습니다.
상황을 정리하고, 개선책을 만들어 주세요.

**Comment by jangxyz** [comment]
#24 이후에, heroku, local, test 의 환경이 달라짐에 따라 별도의 setting file을 나누었습니다.

일명 "heroku 스타일"로 
- `heroku local web`
- `heroku local:run python ./manage.py shell`
- `heroku local:run -e .env.test python ./manage.py test ...`

등을 할 수 있게 되어 있지만, django 기반의 운영을 하기에는 불편합니다.
(예: manage.py command의 추가 옵션 `-h`등을 받지 못함)

"django 스타일"로 할 수 있겠지만,
- 비밀 키 들이 settings.py 에 들어 있지 않아서 `.env` 등의 내용물을 별도로 export를 해야 하고 (local, heroku 에 따라 불러오는 환경이 다름)
- `DJANGO_SETTINGS_MODULE=bookocr.settings.local` 은 너무 길어서 매번 쓰기에도 불편합니다.

heroku 스타일과 django 스타일을 합치면서 손쉽게 운영할 수 있는 환경이 필요합니다.

**Comment by jangxyz** [comment]
### django 기반으로, 더 짧게 입력하도록 환경 변수 추가

(local 세팅 기반)  `bookocr.settings.local` 에서

1. `.env` 파일을 기본으로 읽어들입니다. (heroku 방식과 비밀번호 동기화)
  필요시 `NOENV` 변수가 `ENV=envfile` 변수를 통해 세부 설정을 할 수 있습니다.

2. `BOOKOCR=` 변수로 너무 길었던 `DJANGO_SETTINGS_MODULE=bookocr.settings.` 변수를 대신 해줍니다.
  이제 이렇게만 입력하면 됩니다:

      $ BOOKOCR=local ./manage.py shell


heroku 설정은 비밀번호를 읽어들이지 않습니다. 여전히 따로 세팅해야 합니다 (보안 문제로 놔둠)


PS. heroku 기반에 익숙해져도 될 것 같지만, 나중에 heroku 외에 다른 기반으로 옮길 때를 생각해서라도 기본 django 방식을 유지하려고 합니다.

**Comment by snailzzang** [comment]
아주 좋습니다. 짧고 편리하게 해주셔서 너무나 감사해요!
