### ISSUE TITLE
페이스북 프로필사진  가져와서 뜨게 하기 

### ISSUE THREAD

**Issue by snailzzang** [snailzzang/bookocr#6]

**Comment by jangxyz** [comment]
`profile_picture_url`은 base.html에 적용되었는데 값을 넣는 부분은 `views.home.index` 밖에 없네요.
다른 곳에선 다 이미지가 뜨지 않습니다.

**Comment by jangxyz** [comment]
저의 경우엔 `https://graph.facebook.com/{0}/picture?type=small` 이 주소 말고
`https://graph.facebook.com/{0}/picture` 이게 더 '얼굴이 클로즈업' 돼서 나오는데요. 이걸로 바꾸면 어떨까요?

<img src="https://graph.facebook.com/10208928234018207/picture?type=small" />

<img src="https://graph.facebook.com/10208928234018207/picture" />

**Comment by jangxyz** [comment]
ㅎㅎ... 이것도 작업하셨군요. 이제 위에 `_index`는 없애도 되겠네요.

이제 `index` 메소드 뿐 아니라 **모든 view 메소드에서**도 같은 일이 적용되게 해야 합니다.

다만, 매번 profile_picture_url을 가져와서 context에 넣는 일은 반복적이니까, **자동으로 됐으면** 좋겠습니다.
마치 지금 `user` 변수가 base.html에서 쓰이고 있는데 각 view에서는 `context`로 넘겨주지 않아도 되는 것처럼 말이죠.

[Django Context Objects](https://docs.djangoproject.com/en/1.9/ref/templates/api/#playing-with-context-objects)를 참고해서 완성해주세요.

**Comment by snailzzang** [comment]
Context Objects를 사용해서, 프로필 이미지를 컨텍스트 깊은 곳에 심어놓았습니다. 이제 모든 페이지에서 프로필 이미지가 뜹니다.

**Comment by jangxyz** [comment]
로그인하지 않은 사용자가 접근하면 에러가 납니다.

test code가 추가되었으니 (3f34c00d1a3fd61c0fabf8d610a24195fe91d09b) 고쳐주세요.

**Comment by snailzzang** [comment]
로그인하지 않은 사용자가 접근할 때 첫 화면에서 에러가 나는 문제가 사라졌습니다.

**Comment by jangxyz** [comment]
오홋 `views`에서도 빼셨네요! ^^)_b
